name: Refresh Integration Tokens

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch:

jobs:
  refresh_tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set execute permissions for the script
        run: chmod +x refresh_tokens.sh

      - name: Run refresh token script
        run: ./refresh_tokens.sh
        env:
          REFRESH_API_JWT: ${{ secrets.REFRESH_API_JWT }}
          REFRESH_API_URL: ${{ secrets.REFRESH_API_URL }}
